paypal:
  name:
  client-id:
  mode:
  secret:
  url:
spring:
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable:
    protocol: